point_cloud_topic: "/kea/voxel_grid/output"
map_frame_id: "world"
robot_base_frame_id: "state"
sensor_frame_id: "tof_cam_optical_frame"
robot_pose_with_covariance_topic: "/kea/msf_core/pose"
robot_pose_cache_size: 200
track_point_frame_id: "state"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
